version: "3"
services:
  vitae-bbs-backend:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../:/workspace/vitae-bbs-backend:cached
      - node_modules:/workspace/vitae-bbs-backend/node_modules
      - "~/.aws:/home/vscode/.aws"
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  node_modules: